input_file_name: "/data/lbariogl/flow/LHC23_PbPb_pass4_new/AO2D.root"

input_file_AR_name: "/data/lbariogl/flow/LHC23_PbPb_pass4_new/AnalysisResults.root"

resolution_file_name: "../results_pass4_new/resolution_EP.root"

output_dir_name: "../prova/prova_v2_getCorrectPhi/"
alternative_output_dir_name: "../results_pass4_alternative_new/"
output_file_name: "flow.root"
output_file_name_qc: "qc.root"

nuclei_tree_name: "O2nucleitable"
ep_tree_name: "O2nucleitableflow"

useSP : False

harmonic : 2

mandatory_selections: "fSign < 0 and abs(fEta) < 0.8 and fTPCchi2 > 0.5"
selection_dict:
  {
    "abs(fDCAxy)": "abs(fDCAxy) < 0.1",
    "abs(fDCAz)": "abs(fDCAz) < 1.",
    "fTPCnCls": "fTPCnCls > 99",
    "abs(fZvertex)": "abs(fZvertex) < 10.",
    "fNsigmaITS3He": "fNsigmaITS3He > - 1.5",
    "abs(fNsigmaTPC3He)": "abs(fNsigmaTPC3He) < 2.",
  }
ptdep_selection_dict: # the dictionary has as key the right pt limit for the selection
  {
    "fAvgItsClusSizeCosLambda": {}
    #   2.4: "fAvgItsClusSizeCosLambda > 6",
    #   2.8: "fAvgItsClusSizeCosLambda > 5.5",
    #   100.: "fAvgItsClusSizeCosLambda > 5"
    # }
  }

n_nsigmaTPC_bins: 50
nsigmaTPC_bin_limits: [-5.0, 5.0]

tof_analysis: False

centrality_classes:
  # [[0, 10], [10, 20], [20, 30], [30, 40], [40, 50], [50, 60], [60, 80]]
  [[0, 10], [10, 20], [20, 30], [30, 40], [40, 50], [50, 60]]
  # [[0, 20], [20, 40]]
  # [[0, 10]]

qc_pt_bins: [0., 2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6., 6.4, 6.8, 7.2, 7.6, 8., 10.]

pt_bins:
  [
    [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6., 6.4, 7.2, 8., 10.],
    [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6., 6.4, 7.2, 8., 10.],
    [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6., 6.4, 7.2, 8., 10.],
    [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6., 6.4, 7.2, 8.],
    [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6.4, 7.2, 8.],
    [2, 2.2, 2.4, 2.6, 2.8, 3., 3.2, 3.6, 4., 4.4, 4.8, 5.2, 5.6, 6.4, 7.2],
    # [2, 2.4, 2.8, 3.2, 4., 4.8, 5.6, 6.4],
  ]
  # [
  #   [2, 3, 4.5, 7, 10],
  #   [2, 3, 4.5, 7, 10],
  # ]

cent_colours: [633, 797, 418, 402, 433, 862, 874]

cent_detector_label: "FT0C"
reference_flow_detector: "FT0C"
resolution_flow_detectors: ["TPCl", "TPCr"]

use_Barlow: True

# p_train: [-321.34, 0.6539, 1.591, 0.8225, 2.363]
p_train: [-449.90,
    1.1210,
    1.9451,
    0.7336,
    2.0896,]
resolution_train: 0.09
n_sigma_plot: 5

do_syst: False
n_trials: 500

cut_dict_syst:
  {
    "abs(fDCAxy)": { "cut_greater": False, "cut_list": [0.05, 0.15, 11] },
    "abs(fDCAz)": { "cut_greater": False, "cut_list": [0.75, 1.00, 26] },
    "fTPCnCls": { "cut_greater": True, "cut_list": [100, 130, 7] },
    "abs(fZvertex)": { "cut_greater": False, "cut_list": [8, 10, 5] },
    "fNsigmaITS3He": {"cut_greater": True, "cut_list": [-1.1, -0.9, 5] },
    "abs(fNsigmaTPC3He)": {"cut_greater": False, "cut_list": [2., 1.8, 5] }
  }

n_ptdep_variations_syst: {
  "fAvgItsClusSizeCosLambda" : 0
}

ptdep_cut_dict_syst:
  {
    "fAvgItsClusSizeCosLambda": {}
      # {
      #   2.4: { "cut_greater": True, "cut_list": [5.5, 6.5] },
      #   2.8: { "cut_greater": True, "cut_list": [5., 6.] },
      #   100.: { "cut_greater": True, "cut_list": [4.5, 5.5] },
      # },
  }
